controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      

diff_drive_controller:
  ros__parameters:
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - wheel_left_joint
      - wheel_right_joint
    gains:
